// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      meta: undefined,
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      meta: undefined,
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      meta: undefined,
    },
    "calendar": {
      name: "calendar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/calendar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/calendar.tsx")),
      source: "",
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel": {
      name: "carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/carousel.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/carousel.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      meta: undefined,
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command.tsx")),
      source: "",
      meta: undefined,
    },
    "chart": {
      name: "chart",
      description: "",
      type: "registry:ui",
      registryDependencies: ["card"],
      files: [{
        path: "registry/default/ui/chart.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/chart.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "hover-card": {
      name: "hover-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/hover-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/hover-card.tsx")),
      source: "",
      meta: undefined,
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      meta: undefined,
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      meta: undefined,
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/menubar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/menubar.tsx")),
      source: "",
      meta: undefined,
    },
    "navigation-menu": {
      name: "navigation-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/navigation-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/navigation-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      meta: undefined,
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet": {
      name: "sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "sidebar": {
      name: "sidebar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","separator","sheet","tooltip","input","use-mobile","skeleton"],
      files: [{
        path: "registry/default/ui/sidebar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sidebar.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      meta: undefined,
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      meta: undefined,
    },
    "table": {
      name: "table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/table.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/table.tsx")),
      source: "",
      meta: undefined,
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      meta: undefined,
    },
    "article-02": {
      name: "article-02",
      description: "The Article Two Section for content presentation.",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/article/article-two.tsx",
        type: "registry:component",
        target: "components/shapexui/article-two.tsx"
      }],
      categories: ["article"],
      component: React.lazy(() => import("@/registry/default/blocks/article/article-two.tsx")),
      source: "__registry__/default/blocks/article/article-two.tsx",
      meta: undefined,
    },
    "blog-01": {
      name: "blog-01",
      description: "Blog Grid View",
      type: "registry:block",
      registryDependencies: ["button","badge","input","select","card"],
      files: [{
        path: "registry/default/blocks/blog/blog-01/blog-one.tsx",
        type: "registry:component",
        target: "components/shapexui/blog.tsx"
      },{
        path: "registry/default/blocks/blog/blog-01/blog-header.tsx",
        type: "registry:component",
        target: "components/shapexui/blog-header.tsx"
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog/blog-01/blog-one.tsx")),
      source: "__registry__/default/blocks/blog/blog-01/blog-one.tsx",
      meta: undefined,
    },
    "blog-02": {
      name: "blog-02",
      description: "Simple Blog List",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","input","button"],
      files: [{
        path: "registry/default/blocks/blog/blog-02/blog-two.tsx",
        type: "registry:component",
        target: "components/shapexui/blog.tsx"
      },{
        path: "registry/default/blocks/blog/blog-02/blog-header.tsx",
        type: "registry:component",
        target: "components/shapexui/blog-header.tsx"
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog/blog-02/blog-two.tsx")),
      source: "__registry__/default/blocks/blog/blog-02/blog-two.tsx",
      meta: undefined,
    },
    "contact-01": {
      name: "contact-01",
      description: "A simple Contact Form.",
      type: "registry:block",
      registryDependencies: ["card","button","textarea","input"],
      files: [{
        path: "registry/default/blocks/contact/contact-one.tsx",
        type: "registry:component",
        target: "components/shapexui/contact.tsx"
      }],
      categories: ["contact"],
      component: React.lazy(() => import("@/registry/default/blocks/contact/contact-one.tsx")),
      source: "__registry__/default/blocks/contact/contact-one.tsx",
      meta: undefined,
    },
    "contact-02": {
      name: "contact-02",
      description: "A simple Contact Form.",
      type: "registry:block",
      registryDependencies: ["button","textarea","input","label"],
      files: [{
        path: "registry/default/blocks/contact/contact-two.tsx",
        type: "registry:component",
        target: "components/shapexui/contact.tsx"
      }],
      categories: ["contact"],
      component: React.lazy(() => import("@/registry/default/blocks/contact/contact-two.tsx")),
      source: "__registry__/default/blocks/contact/contact-two.tsx",
      meta: undefined,
    },
    "cta-01": {
      name: "cta-01",
      description: "Call To Action.",
      type: "registry:block",
      registryDependencies: ["button","card"],
      files: [{
        path: "registry/default/blocks/cta/cta-one.tsx",
        type: "registry:component",
        target: "components/shapexui/cta.tsx"
      }],
      categories: ["cta"],
      component: React.lazy(() => import("@/registry/default/blocks/cta/cta-one.tsx")),
      source: "__registry__/default/blocks/cta/cta-one.tsx",
      meta: {"iframeHeight":"410px"},
    },
    "cta-03": {
      name: "cta-03",
      description: "A simple CTA.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/cta/cta-three.tsx",
        type: "registry:component",
        target: "components/shapexui/cta.tsx"
      }],
      categories: ["cta"],
      component: React.lazy(() => import("@/registry/default/blocks/cta/cta-three.tsx")),
      source: "__registry__/default/blocks/cta/cta-three.tsx",
      meta: {"iframeHeight":"629px"},
    },
    "faq-01": {
      name: "faq-01",
      description: "A FQAs block",
      type: "registry:block",
      registryDependencies: ["accordion","badge"],
      files: [{
        path: "registry/default/blocks/faq/faq-01/faq-one.tsx",
        type: "registry:component",
        target: "components/shapexui/faq.tsx"
      },{
        path: "registry/default/blocks/faq/faq-01/tabs.tsx",
        type: "registry:component",
        target: "components/shapexui/tabs.tsx"
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq/faq-01/faq-one.tsx")),
      source: "__registry__/default/blocks/faq/faq-01/faq-one.tsx",
      meta: {"iframeHeight":"600px"},
    },
    "faq-02": {
      name: "faq-02",
      description: "A FAQs.",
      type: "registry:block",
      registryDependencies: ["badge","input"],
      files: [{
        path: "registry/default/blocks/faq/faq-02/faq-two.tsx",
        type: "registry:component",
        target: "components/shapexui/faq.tsx"
      },{
        path: "registry/default/blocks/faq/faq-02/accordion.tsx",
        type: "registry:component",
        target: "components/shapexui/accordion.tsx"
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq/faq-02/faq-two.tsx")),
      source: "__registry__/default/blocks/faq/faq-02/faq-two.tsx",
      meta: {"iframeHeight":"700px"},
    },
    "faq-03": {
      name: "faq-03",
      description: "A FAQs.",
      type: "registry:block",
      registryDependencies: ["card","accordion","label","input","button","textarea"],
      files: [{
        path: "registry/default/blocks/faq/faq-03/faq-three.tsx",
        type: "registry:component",
        target: "components/shapexui/faq.tsx"
      },{
        path: "registry/default/blocks/faq/faq-03/open-contact-form.tsx",
        type: "registry:component",
        target: "components/shapexui/open-contact-form.tsx"
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq/faq-03/faq-three.tsx")),
      source: "__registry__/default/blocks/faq/faq-03/faq-three.tsx",
      meta: {"iframeHeight":"750px"},
    },
    "feature-01": {
      name: "feature-01",
      description: "A Feature Block.",
      type: "registry:block",
      registryDependencies: ["card","accordion"],
      files: [{
        path: "registry/default/blocks/feature/feature-01/feature-one.tsx",
        type: "registry:component",
        target: "components/shapexui/feature.tsx"
      }],
      categories: ["feature"],
      component: React.lazy(() => import("@/registry/default/blocks/feature/feature-01/feature-one.tsx")),
      source: "__registry__/default/blocks/feature/feature-01/feature-one.tsx",
      meta: {"iframeHeight":"500px"},
    },
    "feature-02": {
      name: "feature-02",
      description: "A Feature block.",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/feature/feature-02/feature-two.tsx",
        type: "registry:component",
        target: "components/shapexui/feature.tsx"
      },{
        path: "registry/default/blocks/feature/feature-02/video-dialog.tsx",
        type: "registry:component",
        target: "components/shapexui/video-dialog.tsx"
      }],
      categories: ["feature"],
      component: React.lazy(() => import("@/registry/default/blocks/feature/feature-02/feature-two.tsx")),
      source: "__registry__/default/blocks/feature/feature-02/feature-two.tsx",
      meta: {"iframeHeight":"797px"},
    },
    "footer-01": {
      name: "footer-01",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/footer/footer-01/footer-one.tsx",
        type: "registry:component",
        target: "components/shapexui/footer.tsx"
      },{
        path: "registry/default/blocks/footer/footer-01/animation-container.tsx",
        type: "registry:component",
        target: "components/shapexui/animation-container.tsx"
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer/footer-01/footer-one.tsx")),
      source: "__registry__/default/blocks/footer/footer-01/footer-one.tsx",
      meta: {"iframeHeight":"250px"},
    },
    "footer-02": {
      name: "footer-02",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/footer/footer-02/footer-two.tsx",
        type: "registry:component",
        target: "components/shapexui/footer.tsx"
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer/footer-02/footer-two.tsx")),
      source: "__registry__/default/blocks/footer/footer-02/footer-two.tsx",
      meta: {"iframeHeight":"462px"},
    },
    "footer-03": {
      name: "footer-03",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/footer/footer-03/footer-three.tsx",
        type: "registry:component",
        target: "components/shapexui/footer.tsx"
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer/footer-03/footer-three.tsx")),
      source: "__registry__/default/blocks/footer/footer-03/footer-three.tsx",
      meta: {"iframeHeight":"460px"},
    },
    "header-01": {
      name: "header-01",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["sheet","button"],
      files: [{
        path: "registry/default/blocks/header/header-01/header-one.tsx",
        type: "registry:component",
        target: "components/shapexui/header.tsx"
      },{
        path: "registry/default/blocks/header/header-01/animation-container.tsx",
        type: "registry:component",
        target: "components/shapexui/animation-container.tsx"
      },{
        path: "registry/default/blocks/header/header-01/mobile-navbar.tsx",
        type: "registry:component",
        target: "components/shapexui/mobile-navbar.tsx"
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header/header-01/header-one.tsx")),
      source: "__registry__/default/blocks/header/header-01/header-one.tsx",
      meta: {"iframeHeight":"300px"},
    },
    "header-02": {
      name: "header-02",
      description: "header block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/header/header-02/header-two.tsx",
        type: "registry:component",
        target: "components/shapexui/header.tsx"
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header/header-02/header-two.tsx")),
      source: "__registry__/default/blocks/header/header-02/header-two.tsx",
      meta: {"iframeHeight":"300px"},
    },
    "header-03": {
      name: "header-03",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["button","sheet","navigation-menu"],
      files: [{
        path: "registry/default/blocks/header/header-03/header-three.tsx",
        type: "registry:component",
        target: "components/shapexui/header.tsx"
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header/header-03/header-three.tsx")),
      source: "__registry__/default/blocks/header/header-03/header-three.tsx",
      meta: {"iframeHeight":"300px"},
    },
    "header-04": {
      name: "header-04",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["button","label","input","select","sheet"],
      files: [{
        path: "registry/default/blocks/header/header-04/header-four.tsx",
        type: "registry:component",
        target: "components/shapexui/header.tsx"
      },{
        path: "registry/default/blocks/header/header-04/contact-form.tsx",
        type: "registry:component",
        target: "components/shapexui/contact-form.tsx"
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header/header-04/header-four.tsx")),
      source: "__registry__/default/blocks/header/header-04/header-four.tsx",
      meta: {"iframeHeight":"400px"},
    },
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/login/login-01/login-form.tsx",
        type: "registry:component",
        target: "components/shapexui/login.tsx"
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login/login-01/login-form.tsx")),
      source: "__registry__/default/blocks/login/login-01/login-form.tsx",
      meta: {"iframeHeight":"530px"},
    },
    "login-02": {
      name: "login-02",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","separator"],
      files: [{
        path: "registry/default/blocks/login/login-02/login-form-two.tsx",
        type: "registry:component",
        target: "components/shapexui/login.tsx"
      },{
        path: "registry/default/blocks/login/login-02/google-logo.tsx",
        type: "registry:component",
        target: "components/shapexui/google-logo.tsx"
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login/login-02/login-form-two.tsx")),
      source: "__registry__/default/blocks/login/login-02/login-form-two.tsx",
      meta: {"iframeHeight":"625px"},
    },
    "logo-01": {
      name: "logo-01",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/logo/logo-01/logo-one.tsx",
        type: "registry:component",
        target: "components/shapexui/logo.tsx"
      },{
        path: "registry/default/blocks/logo/logo-01/marquee.tsx",
        type: "registry:component",
        target: "components/shapexui/marquee.tsx"
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo/logo-01/logo-one.tsx")),
      source: "__registry__/default/blocks/logo/logo-01/logo-one.tsx",
      meta: {"iframeHeight":"230px"},
    },
    "logo-02": {
      name: "logo-02",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/logo/logo-02/logo-two.tsx",
        type: "registry:component",
        target: "components/shapexui/logo.tsx"
      },{
        path: "registry/default/blocks/logo/logo-02/marquee.tsx",
        type: "registry:component",
        target: "components/shapexui/marquee.tsx"
      },{
        path: "registry/default/blocks/logo/logo-02/tailwind.config.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo/logo-02/logo-two.tsx")),
      source: "__registry__/default/blocks/logo/logo-02/logo-two.tsx",
      meta: {"iframeHeight":"460px"},
    },
    "logo-03": {
      name: "logo-03",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/logo/logo-03/logo-three.tsx",
        type: "registry:component",
        target: "components/shapexui/logo.tsx"
      },{
        path: "registry/default/blocks/logo/logo-03/logo-slider.tsx",
        type: "registry:component",
        target: "components/shapexui/logo-slider.tsx"
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo/logo-03/logo-three.tsx")),
      source: "__registry__/default/blocks/logo/logo-03/logo-three.tsx",
      meta: {"iframeHeight":"495px"},
    },
    "newsletter-01": {
      name: "newsletter-01",
      description: "newsletter block 1",
      type: "registry:block",
      registryDependencies: ["input","button"],
      files: [{
        path: "registry/default/blocks/newsletter/newsletter-01/newsletter-one.tsx",
        type: "registry:component",
        target: "components/shapexui/newsletter.tsx"
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter/newsletter-01/newsletter-one.tsx")),
      source: "__registry__/default/blocks/newsletter/newsletter-01/newsletter-one.tsx",
      meta: {"iframeHeight":"442px"},
    },
    "newsletter-02": {
      name: "newsletter-02",
      description: "newsletter block 2",
      type: "registry:block",
      registryDependencies: ["badge"],
      files: [{
        path: "registry/default/blocks/newsletter/newsletter-02/newsletter-two.tsx",
        type: "registry:component",
        target: "components/shapexui/newsletter.tsx"
      },{
        path: "registry/default/blocks/newsletter/newsletter-02/user-image.tsx",
        type: "registry:component",
        target: "components/shapexui/user-image.tsx"
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter/newsletter-02/newsletter-two.tsx")),
      source: "__registry__/default/blocks/newsletter/newsletter-02/newsletter-two.tsx",
      meta: {"iframeHeight":"570px"},
    },
    "newsletter-03": {
      name: "newsletter-03",
      description: "newsletter block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/newsletter/newsletter-03/newsletter-three.tsx",
        type: "registry:component",
        target: "components/shapexui/newsletter.tsx"
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter/newsletter-03/newsletter-three.tsx")),
      source: "__registry__/default/blocks/newsletter/newsletter-03/newsletter-three.tsx",
      meta: {"iframeHeight":"368px"},
    },
    "pricing-01": {
      name: "pricing-01",
      description: "pricing block 1",
      type: "registry:block",
      registryDependencies: ["card","button","switch"],
      files: [{
        path: "registry/default/blocks/pricing/pricing-01/pricing-one.tsx",
        type: "registry:component",
        target: "components/shapexui/pricing.tsx"
      },{
        path: "registry/default/blocks/pricing/pricing-01/price-slider.tsx",
        type: "registry:component",
        target: "components/shapexui/price-slider.tsx"
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing/pricing-01/pricing-one.tsx")),
      source: "__registry__/default/blocks/pricing/pricing-01/pricing-one.tsx",
      meta: undefined,
    },
    "pricing-02": {
      name: "pricing-02",
      description: "pricing block 2",
      type: "registry:block",
      registryDependencies: ["button","card"],
      files: [{
        path: "registry/default/blocks/pricing/pricing-02/pricing-two.tsx",
        type: "registry:component",
        target: "components/shapexui/pricing.tsx"
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing/pricing-02/pricing-two.tsx")),
      source: "__registry__/default/blocks/pricing/pricing-02/pricing-two.tsx",
      meta: undefined,
    },
    "pricing-03": {
      name: "pricing-03",
      description: "pricing block 3",
      type: "registry:block",
      registryDependencies: ["card","badge","button"],
      files: [{
        path: "registry/default/blocks/pricing/pricing-03/pricing-three.tsx",
        type: "registry:component",
        target: "components/shapexui/pricing.tsx"
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing/pricing-03/pricing-three.tsx")),
      source: "__registry__/default/blocks/pricing/pricing-03/pricing-three.tsx",
      meta: {"iframeHeight":"670px"},
    },
    "pricing-04": {
      name: "pricing-04",
      description: "pricing block 4",
      type: "registry:block",
      registryDependencies: ["button","card"],
      files: [{
        path: "registry/default/blocks/pricing/pricing-04/pricing-four.tsx",
        type: "registry:component",
        target: "components/shapexui/pricing.tsx"
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing/pricing-04/pricing-four.tsx")),
      source: "__registry__/default/blocks/pricing/pricing-04/pricing-four.tsx",
      meta: {"iframeHeight":"740px"},
    },
    "rating-01": {
      name: "rating-01",
      description: "rating block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/rating/rating-01/rating-one.tsx",
        type: "registry:component",
        target: "components/shapexui/rating.tsx"
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating/rating-01/rating-one.tsx")),
      source: "__registry__/default/blocks/rating/rating-01/rating-one.tsx",
      meta: {"iframeHeight":"300px"},
    },
    "rating-02": {
      name: "rating-02",
      description: "rating block 2",
      type: "registry:block",
      registryDependencies: ["input","card","label","button"],
      files: [{
        path: "registry/default/blocks/rating/rating-02/rating-two.tsx",
        type: "registry:component",
        target: "components/shapexui/rating.tsx"
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating/rating-02/rating-two.tsx")),
      source: "__registry__/default/blocks/rating/rating-02/rating-two.tsx",
      meta: {"iframeHeight":"550px"},
    },
    "rating-03": {
      name: "rating-03",
      description: "rating block 3",
      type: "registry:block",
      registryDependencies: ["avatar","button","progress","card","select","checkbox","textarea","label","input"],
      files: [{
        path: "registry/default/blocks/rating/rating-03/rating-three.tsx",
        type: "registry:component",
        target: "components/shapexui/rating.tsx"
      },{
        path: "registry/default/blocks/rating/rating-03/dialog-box.tsx",
        type: "registry:component",
        target: "components/shapexui/dialog-box.tsx"
      },{
        path: "registry/default/blocks/rating/rating-03/write-review.tsx",
        type: "registry:component",
        target: "components/shapexui/write-review.tsx"
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating/rating-03/rating-three.tsx")),
      source: "__registry__/default/blocks/rating/rating-03/rating-three.tsx",
      meta: {"iframeHeight":"610px"},
    },
    "roadmap-01": {
      name: "roadmap-01",
      description: "roadmap block 1",
      type: "registry:block",
      registryDependencies: ["badge","card","progress"],
      files: [{
        path: "registry/default/blocks/roadmap/roadmap-01/roadmap-one.tsx",
        type: "registry:component",
        target: "components/shapexui/roadmap.tsx"
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap/roadmap-01/roadmap-one.tsx")),
      source: "__registry__/default/blocks/roadmap/roadmap-01/roadmap-one.tsx",
      meta: {"iframeHeight":"650px"},
    },
    "roadmap-02": {
      name: "roadmap-02",
      description: "roadmap block 2",
      type: "registry:block",
      registryDependencies: ["badge","progress","card"],
      files: [{
        path: "registry/default/blocks/roadmap/roadmap-02/roadmap-two.tsx",
        type: "registry:component",
        target: "components/shapexui/roadmap.tsx"
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap/roadmap-02/roadmap-two.tsx")),
      source: "__registry__/default/blocks/roadmap/roadmap-02/roadmap-two.tsx",
      meta: undefined,
    },
    "roadmap-03": {
      name: "roadmap-03",
      description: "roadmap block 3",
      type: "registry:block",
      registryDependencies: ["checkbox"],
      files: [{
        path: "registry/default/blocks/roadmap/roadmap-03/roadmap-three.tsx",
        type: "registry:component",
        target: "components/shapexui/roadmap.tsx"
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap/roadmap-03/roadmap-three.tsx")),
      source: "__registry__/default/blocks/roadmap/roadmap-03/roadmap-three.tsx",
      meta: {"iframeHeight":"550px"},
    },
    "stats-01": {
      name: "stats-01",
      description: "stats block 3",
      type: "registry:block",
      registryDependencies: ["card"],
      files: [{
        path: "registry/default/blocks/stats/stats-01/stats-one.tsx",
        type: "registry:component",
        target: "components/shapexui/stats.tsx"
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats/stats-01/stats-one.tsx")),
      source: "__registry__/default/blocks/stats/stats-01/stats-one.tsx",
      meta: {"iframeHeight":"467px"},
    },
    "stats-02": {
      name: "stats-02",
      description: "stats block 2",
      type: "registry:block",
      registryDependencies: ["card","button"],
      files: [{
        path: "registry/default/blocks/stats/stats-02/stats-two.tsx",
        type: "registry:component",
        target: "components/shapexui/stats.tsx"
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats/stats-02/stats-two.tsx")),
      source: "__registry__/default/blocks/stats/stats-02/stats-two.tsx",
      meta: {"iframeHeight":"345px"},
    },
    "stats-03": {
      name: "stats-03",
      description: "stats block 3",
      type: "registry:block",
      registryDependencies: ["button","card"],
      files: [{
        path: "registry/default/blocks/stats/stats-03/stats-three.tsx",
        type: "registry:component",
        target: "components/shapexui/stats.tsx"
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats/stats-03/stats-three.tsx")),
      source: "__registry__/default/blocks/stats/stats-03/stats-three.tsx",
      meta: {"iframeHeight":"420px"},
    },
    "steps-01": {
      name: "steps-01",
      description: "steps block 1",
      type: "registry:block",
      registryDependencies: ["button","card","switch"],
      files: [{
        path: "registry/default/blocks/steps/steps-01/steps-one.tsx",
        type: "registry:component",
        target: "components/shapexui/steps.tsx"
      }],
      categories: ["steps"],
      component: React.lazy(() => import("@/registry/default/blocks/steps/steps-01/steps-one.tsx")),
      source: "__registry__/default/blocks/steps/steps-01/steps-one.tsx",
      meta: undefined,
    },
    "steps-02": {
      name: "steps-02",
      description: "steps block 2",
      type: "registry:block",
      registryDependencies: ["button","card","input","select","label","textarea"],
      files: [{
        path: "registry/default/blocks/steps/steps-02/steps-two.tsx",
        type: "registry:component",
        target: "components/shapexui/steps.tsx"
      }],
      categories: ["steps"],
      component: React.lazy(() => import("@/registry/default/blocks/steps/steps-02/steps-two.tsx")),
      source: "__registry__/default/blocks/steps/steps-02/steps-two.tsx",
      meta: undefined,
    },
    "signup-01": {
      name: "signup-01",
      description: "A simple Signup form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/signup/signup-01/signup-one.tsx",
        type: "registry:component",
        target: "components/shapexui/signup.tsx"
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup/signup-01/signup-one.tsx")),
      source: "__registry__/default/blocks/signup/signup-01/signup-one.tsx",
      meta: undefined,
    },
    "signup-02": {
      name: "signup-02",
      description: "A Signup form with Password Validation.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","hover-card"],
      files: [{
        path: "registry/default/blocks/signup/signup-02/signup-two.tsx",
        type: "registry:component",
        target: "components/shapexui/signup.tsx"
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup/signup-02/signup-two.tsx")),
      source: "__registry__/default/blocks/signup/signup-02/signup-two.tsx",
      meta: {"iframeHeight":"750px"},
    },
    "signup-03": {
      name: "signup-03",
      description: "A Signup form with Step",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/default/blocks/signup/signup-03/signup-three.tsx",
        type: "registry:component",
        target: "components/shapexui/signup.tsx"
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup/signup-03/signup-three.tsx")),
      source: "__registry__/default/blocks/signup/signup-03/signup-three.tsx",
      meta: {"iframeHeight":"650px"},
    },
    "signup-04": {
      name: "signup-04",
      description: "A Signup form",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","checkbox"],
      files: [{
        path: "registry/default/blocks/signup/signup-04/signup-four.tsx",
        type: "registry:component",
        target: "components/shapexui/signup.tsx"
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup/signup-04/signup-four.tsx")),
      source: "__registry__/default/blocks/signup/signup-04/signup-four.tsx",
      meta: undefined,
    },
    "team-01": {
      name: "team-01",
      description: "team block 1",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/team/team-01/team-one.tsx",
        type: "registry:component",
        target: "components/shapexui/team.tsx"
      }],
      categories: ["teams"],
      component: React.lazy(() => import("@/registry/default/blocks/team/team-01/team-one.tsx")),
      source: "__registry__/default/blocks/team/team-01/team-one.tsx",
      meta: undefined,
    },
    "team-02": {
      name: "team-02",
      description: "team block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/team/team-02/team-two.tsx",
        type: "registry:component",
        target: "components/shapexui/team.tsx"
      },{
        path: "registry/default/blocks/team/team-02/team-card.tsx",
        type: "registry:component",
        target: "components/shapexui/team-card.tsx"
      }],
      categories: ["teams"],
      component: React.lazy(() => import("@/registry/default/blocks/team/team-02/team-two.tsx")),
      source: "__registry__/default/blocks/team/team-02/team-two.tsx",
      meta: undefined,
    },
    "team-03": {
      name: "team-03",
      description: "team block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/team/team-03/team-three.tsx",
        type: "registry:component",
        target: "components/shapexui/team.tsx"
      },{
        path: "registry/default/blocks/team/team-03/marquee.tsx",
        type: "registry:component",
        target: "components/shapexui/marquee.tsx"
      },{
        path: "registry/default/blocks/team/team-03/tailwind.config.ts",
        type: "registry:component",
        target: ""
      }],
      categories: ["teams"],
      component: React.lazy(() => import("@/registry/default/blocks/team/team-03/team-three.tsx")),
      source: "__registry__/default/blocks/team/team-03/team-three.tsx",
      meta: {"iframeHeight":"640px"},
    },
    "testimonial-02": {
      name: "testimonial-02",
      description: "testimonial block 1",
      type: "registry:block",
      registryDependencies: ["carousel"],
      files: [{
        path: "registry/default/blocks/testimonial/testimonial-02/testimonial-two.tsx",
        type: "registry:component",
        target: "components/shapexui/testimonial.tsx"
      },{
        path: "registry/default/blocks/testimonial/testimonial-02/testimonial-card.tsx",
        type: "registry:component",
        target: "components/shapexui/testimonial-card.tsx"
      }],
      categories: ["testimonial"],
      component: React.lazy(() => import("@/registry/default/blocks/testimonial/testimonial-02/testimonial-two.tsx")),
      source: "__registry__/default/blocks/testimonial/testimonial-02/testimonial-two.tsx",
      meta: {"iframeHeight":"560px"},
    },
    "testimonial-03": {
      name: "testimonial-03",
      description: "testimonial block 3",
      type: "registry:block",
      registryDependencies: ["avatar","button","card"],
      files: [{
        path: "registry/default/blocks/testimonial/testimonial-03/testimonial-three.tsx",
        type: "registry:component",
        target: "components/shapexui/testimonial.tsx"
      }],
      categories: ["testimonial"],
      component: React.lazy(() => import("@/registry/default/blocks/testimonial/testimonial-03/testimonial-three.tsx")),
      source: "__registry__/default/blocks/testimonial/testimonial-03/testimonial-three.tsx",
      meta: {"iframeHeight":"560px"},
    },
    "analytics": {
      name: "analytics",
      description: "Analytics dashboard",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/full-featured/analytics/page.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/app-sidebar.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/nav-main.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/nav-user.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/analytics-chart.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/customer-table.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/analytics/components/info-card.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["analytics"],
      component: React.lazy(() => import("@/registry/default/blocks/full-featured/analytics/page.tsx")),
      source: "__registry__/default/blocks/full-featured/analytics/page.tsx",
      meta: {"iframeHeight":"820px"},
    },
    "e-commerce": {
      name: "e-commerce",
      description: "e-commerce page",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/full-featured/e-commerce/page.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/e-commerce/components/category-carousel.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/e-commerce/components/Ecommerce.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/e-commerce/components/hero-carousel.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/e-commerce/components/popular-product-card.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/e-commerce/components/product-card.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["e-commerce"],
      component: React.lazy(() => import("@/registry/default/blocks/full-featured/e-commerce/page.tsx")),
      source: "__registry__/default/blocks/full-featured/e-commerce/page.tsx",
      meta: {"iframeHeight":"1100px"},
    },
    "file-management": {
      name: "file-management",
      description: "file-management page",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/full-featured/file-management/page.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/file-management/components/file-manager.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/file-management/components/file-table.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/file-management/hook/useFileManager.ts",
        type: "registry:hook",
        target: ""
      },{
        path: "registry/default/blocks/full-featured/file-management/types/types.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: ["file-manager"],
      component: React.lazy(() => import("@/registry/default/blocks/full-featured/file-management/page.tsx")),
      source: "__registry__/default/blocks/full-featured/file-management/page.tsx",
      meta: {"iframeHeight":"700px"},
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
  },
}
