// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      meta: undefined,
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      meta: undefined,
    },
    "calendar": {
      name: "calendar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/calendar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/calendar.tsx")),
      source: "",
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      meta: undefined,
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "hover-card": {
      name: "hover-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/hover-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/hover-card.tsx")),
      source: "",
      meta: undefined,
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      meta: undefined,
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      meta: undefined,
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/menubar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/menubar.tsx")),
      source: "",
      meta: undefined,
    },
    "navigation-menu": {
      name: "navigation-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/navigation-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/navigation-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      meta: undefined,
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet": {
      name: "sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "sidebar": {
      name: "sidebar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","separator","sheet","tooltip","input","use-mobile","skeleton"],
      files: [{
        path: "registry/default/ui/sidebar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sidebar.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      meta: undefined,
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      meta: undefined,
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      meta: undefined,
    },
    "article-01": {
      name: "article-01",
      description: "The Article Section for content presentation.",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/article-01/page.tsx",
        type: "registry:page",
        target: "app/article/page.tsx"
      },{
        path: "registry/default/blocks/article-01/components/article-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["article"],
      component: React.lazy(() => import("@/registry/default/blocks/article-01/page.tsx")),
      source: "__registry__/default/blocks/article-01/page.tsx",
      meta: undefined,
    },
    "article-02": {
      name: "article-02",
      description: "The Article Two Section for content presentation.",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/article-02/page.tsx",
        type: "registry:page",
        target: "app/article/page.tsx"
      },{
        path: "registry/default/blocks/article-02/components/article-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["article"],
      component: React.lazy(() => import("@/registry/default/blocks/article-02/page.tsx")),
      source: "__registry__/default/blocks/article-02/page.tsx",
      meta: undefined,
    },
    "blog-01": {
      name: "blog-01",
      description: "Blog Grid View",
      type: "registry:block",
      registryDependencies: ["card","button","badge"],
      files: [{
        path: "registry/default/blocks/blog-01/page.tsx",
        type: "registry:page",
        target: "app/blog/page.tsx"
      },{
        path: "registry/default/blocks/blog-01/components/blog-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-01/components/blog-header.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-01/hook/use-outside-click.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog-01/page.tsx")),
      source: "__registry__/default/blocks/blog-01/page.tsx",
      meta: undefined,
    },
    "blog-02": {
      name: "blog-02",
      description: "Simple Blog List",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/blog-02/page.tsx",
        type: "registry:page",
        target: "app/blog/page.tsx"
      },{
        path: "registry/default/blocks/blog-02/components/blog-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-02/components/blog-header.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog-02/page.tsx")),
      source: "__registry__/default/blocks/blog-02/page.tsx",
      meta: undefined,
    },
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/login-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/login-01/components/login-form.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login-01/page.tsx")),
      source: "__registry__/default/blocks/login-01/page.tsx",
      meta: undefined,
    },
    "login-02": {
      name: "login-02",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/login-02/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/login-02/components/login-form-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/login-02/components/google-logo.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login-02/page.tsx")),
      source: "__registry__/default/blocks/login-02/page.tsx",
      meta: undefined,
    },
    "signup-01": {
      name: "signup-01",
      description: "A simple Signup form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/signup-01/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-01/components/signup-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-01/page.tsx")),
      source: "__registry__/default/blocks/signup-01/page.tsx",
      meta: undefined,
    },
    "signup-02": {
      name: "signup-02",
      description: "A Signup form with Password Validation.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","hover-card"],
      files: [{
        path: "registry/default/blocks/signup-02/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-02/components/signup-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-02/page.tsx")),
      source: "__registry__/default/blocks/signup-02/page.tsx",
      meta: undefined,
    },
    "signup-03": {
      name: "signup-03",
      description: "A Signup form with Step",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/default/blocks/signup-03/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-03/components/signup-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-03/page.tsx")),
      source: "__registry__/default/blocks/signup-03/page.tsx",
      meta: undefined,
    },
    "signup-04": {
      name: "signup-04",
      description: "A Signup form",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","checkbox"],
      files: [{
        path: "registry/default/blocks/signup-04/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-04/components/signup-four.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-04/page.tsx")),
      source: "__registry__/default/blocks/signup-04/page.tsx",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
  },
}
