// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      meta: undefined,
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert.tsx")),
      source: "",
      meta: undefined,
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      meta: undefined,
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      meta: undefined,
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      meta: undefined,
    },
    "calendar": {
      name: "calendar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/ui/calendar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/calendar.tsx")),
      source: "",
      meta: undefined,
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      meta: undefined,
    },
    "carousel": {
      name: "carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/carousel.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/carousel.tsx")),
      source: "",
      meta: undefined,
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      meta: undefined,
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      meta: undefined,
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [{
        path: "registry/default/ui/command.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command.tsx")),
      source: "",
      meta: undefined,
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "hover-card": {
      name: "hover-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/hover-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/hover-card.tsx")),
      source: "",
      meta: undefined,
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      meta: undefined,
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      meta: undefined,
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/menubar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/menubar.tsx")),
      source: "",
      meta: undefined,
    },
    "navigation-menu": {
      name: "navigation-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/navigation-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/navigation-menu.tsx")),
      source: "",
      meta: undefined,
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      meta: undefined,
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      meta: undefined,
    },
    "sheet": {
      name: "sheet",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/sheet.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sheet.tsx")),
      source: "",
      meta: undefined,
    },
    "sidebar": {
      name: "sidebar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button","separator","sheet","tooltip","input","use-mobile","skeleton"],
      files: [{
        path: "registry/default/ui/sidebar.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/sidebar.tsx")),
      source: "",
      meta: undefined,
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      meta: undefined,
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      meta: undefined,
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      meta: undefined,
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle"],
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      meta: undefined,
    },
    "article-01": {
      name: "article-01",
      description: "The Article Section for content presentation.",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/article-01/page.tsx",
        type: "registry:page",
        target: "app/article/page.tsx"
      },{
        path: "registry/default/blocks/article-01/components/article-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["article"],
      component: React.lazy(() => import("@/registry/default/blocks/article-01/page.tsx")),
      source: "__registry__/default/blocks/article-01/page.tsx",
      meta: undefined,
    },
    "article-02": {
      name: "article-02",
      description: "The Article Two Section for content presentation.",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/article-02/page.tsx",
        type: "registry:page",
        target: "app/article/page.tsx"
      },{
        path: "registry/default/blocks/article-02/components/article-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["article"],
      component: React.lazy(() => import("@/registry/default/blocks/article-02/page.tsx")),
      source: "__registry__/default/blocks/article-02/page.tsx",
      meta: undefined,
    },
    "blog-01": {
      name: "blog-01",
      description: "Blog Grid View",
      type: "registry:block",
      registryDependencies: ["card","button","badge"],
      files: [{
        path: "registry/default/blocks/blog-01/page.tsx",
        type: "registry:page",
        target: "app/blog/page.tsx"
      },{
        path: "registry/default/blocks/blog-01/components/blog-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-01/components/blog-header.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-01/hook/use-outside-click.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog-01/page.tsx")),
      source: "__registry__/default/blocks/blog-01/page.tsx",
      meta: undefined,
    },
    "blog-02": {
      name: "blog-02",
      description: "Simple Blog List",
      type: "registry:block",
      registryDependencies: ["card","badge","separator","scroll-area"],
      files: [{
        path: "registry/default/blocks/blog-02/page.tsx",
        type: "registry:page",
        target: "app/blog/page.tsx"
      },{
        path: "registry/default/blocks/blog-02/components/blog-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/blog-02/components/blog-header.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["blog"],
      component: React.lazy(() => import("@/registry/default/blocks/blog-02/page.tsx")),
      source: "__registry__/default/blocks/blog-02/page.tsx",
      meta: undefined,
    },
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/login-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/login-01/components/login-form.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login-01/page.tsx")),
      source: "__registry__/default/blocks/login-01/page.tsx",
      meta: undefined,
    },
    "contact-01": {
      name: "contact-01",
      description: "A simple Contact Form.",
      type: "registry:block",
      registryDependencies: ["button","textarea","input","label"],
      files: [{
        path: "registry/default/blocks/contact-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/contact-01/components/contact-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["contact"],
      component: React.lazy(() => import("@/registry/default/blocks/contact-01/page.tsx")),
      source: "__registry__/default/blocks/contact-01/page.tsx",
      meta: undefined,
    },
    "contact-02": {
      name: "contact-02",
      description: "A simple Contact Form.",
      type: "registry:block",
      registryDependencies: ["button","textarea","input","label"],
      files: [{
        path: "registry/default/blocks/contact-02/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/contact-02/components/contact-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["contact"],
      component: React.lazy(() => import("@/registry/default/blocks/contact-02/page.tsx")),
      source: "__registry__/default/blocks/contact-02/page.tsx",
      meta: undefined,
    },
    "cta-01": {
      name: "cta-01",
      description: "Call To Action.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/cta-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/cta-01/components/cta-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["cta"],
      component: React.lazy(() => import("@/registry/default/blocks/cta-01/page.tsx")),
      source: "__registry__/default/blocks/cta-01/page.tsx",
      meta: undefined,
    },
    "cta-02": {
      name: "cta-02",
      description: "A simple Contact Form.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/cta-02/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/cta-02/components/cta-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/cta-02/components/user-image.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["cta"],
      component: React.lazy(() => import("@/registry/default/blocks/cta-02/page.tsx")),
      source: "__registry__/default/blocks/cta-02/page.tsx",
      meta: undefined,
    },
    "cta-03": {
      name: "cta-03",
      description: "A simple CTA.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/cta-03/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/cta-03/components/cta-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["cta"],
      component: React.lazy(() => import("@/registry/default/blocks/cta-03/page.tsx")),
      source: "__registry__/default/blocks/cta-03/page.tsx",
      meta: undefined,
    },
    "faq-01": {
      name: "faq-01",
      description: "A FQAs block",
      type: "registry:block",
      registryDependencies: ["tabs","accordion","badge"],
      files: [{
        path: "registry/default/blocks/faq-01/page.tsx",
        type: "registry:page",
        target: "app/faq/page.tsx"
      },{
        path: "registry/default/blocks/faq-01/components/faq-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/faq-01/components/tabs.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq-01/page.tsx")),
      source: "__registry__/default/blocks/faq-01/page.tsx",
      meta: undefined,
    },
    "faq-02": {
      name: "faq-02",
      description: "A FAQs.",
      type: "registry:block",
      registryDependencies: ["badge","input"],
      files: [{
        path: "registry/default/blocks/faq-02/page.tsx",
        type: "registry:page",
        target: "app/faq/page.tsx"
      },{
        path: "registry/default/blocks/faq-02/components/faq-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/faq-02/components/accordion.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq-02/page.tsx")),
      source: "__registry__/default/blocks/faq-02/page.tsx",
      meta: undefined,
    },
    "faq-03": {
      name: "faq-03",
      description: "A FAQs.",
      type: "registry:block",
      registryDependencies: ["card"],
      files: [{
        path: "registry/default/blocks/faq-03/page.tsx",
        type: "registry:page",
        target: "app/faq/page.tsx"
      },{
        path: "registry/default/blocks/faq-03/components/faq-three.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/faq-03/components/open-contact-form.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/faq-03/hook/use-outside-click.ts",
        type: "registry:hook",
        target: ""
      }],
      categories: ["faq"],
      component: React.lazy(() => import("@/registry/default/blocks/faq-03/page.tsx")),
      source: "__registry__/default/blocks/faq-03/page.tsx",
      meta: undefined,
    },
    "feature-01": {
      name: "feature-01",
      description: "A Feature Block.",
      type: "registry:block",
      registryDependencies: ["card","accordion"],
      files: [{
        path: "registry/default/blocks/feature-01/page.tsx",
        type: "registry:page",
        target: "app/feature/page.tsx"
      },{
        path: "registry/default/blocks/feature-01/components/feature-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["feature"],
      component: React.lazy(() => import("@/registry/default/blocks/feature-01/page.tsx")),
      source: "__registry__/default/blocks/feature-01/page.tsx",
      meta: undefined,
    },
    "feature-02": {
      name: "feature-02",
      description: "A Feature block.",
      type: "registry:block",
      registryDependencies: ["card","accordion"],
      files: [{
        path: "registry/default/blocks/feature-02/page.tsx",
        type: "registry:page",
        target: "app/feature/page.tsx"
      },{
        path: "registry/default/blocks/feature-02/components/feature-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/feature-02/components/video-dialog.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["feature"],
      component: React.lazy(() => import("@/registry/default/blocks/feature-02/page.tsx")),
      source: "__registry__/default/blocks/feature-02/page.tsx",
      meta: undefined,
    },
    "feature-03": {
      name: "feature-03",
      description: "A Feature block.",
      type: "registry:block",
      registryDependencies: ["card"],
      files: [{
        path: "registry/default/blocks/feature-03/page.tsx",
        type: "registry:page",
        target: "app/feature/page.tsx"
      },{
        path: "registry/default/blocks/feature-03/components/feature-three.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/feature-03/components/video-dialog.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["feature"],
      component: React.lazy(() => import("@/registry/default/blocks/feature-03/page.tsx")),
      source: "__registry__/default/blocks/feature-03/page.tsx",
      meta: undefined,
    },
    "footer-01": {
      name: "footer-01",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/blocks/footer-01/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx"
      },{
        path: "registry/default/blocks/footer-01/components/footer-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/footer-01/components/animation-container.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer-01/page.tsx")),
      source: "__registry__/default/blocks/footer-01/page.tsx",
      meta: undefined,
    },
    "footer-02": {
      name: "footer-02",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/footer-02/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx"
      },{
        path: "registry/default/blocks/footer-02/components/footer-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer-02/page.tsx")),
      source: "__registry__/default/blocks/footer-02/page.tsx",
      meta: undefined,
    },
    "footer-03": {
      name: "footer-03",
      description: "A Footer block.",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/footer-03/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx"
      },{
        path: "registry/default/blocks/footer-03/components/footer-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["footer"],
      component: React.lazy(() => import("@/registry/default/blocks/footer-03/page.tsx")),
      source: "__registry__/default/blocks/footer-03/page.tsx",
      meta: undefined,
    },
    "header-01": {
      name: "header-01",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["sheet","button"],
      files: [{
        path: "registry/default/blocks/header-01/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/header-01/components/header-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/header-01/components/animation-container.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/header-01/components/mobile-navbar.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header-01/page.tsx")),
      source: "__registry__/default/blocks/header-01/page.tsx",
      meta: undefined,
    },
    "header-02": {
      name: "header-02",
      description: "header block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/header-02/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/header-02/components/header-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header-02/page.tsx")),
      source: "__registry__/default/blocks/header-02/page.tsx",
      meta: undefined,
    },
    "header-03": {
      name: "header-03",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["button","sheet","navigation-menu"],
      files: [{
        path: "registry/default/blocks/header-03/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/header-03/components/header-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header-03/page.tsx")),
      source: "__registry__/default/blocks/header-03/page.tsx",
      meta: undefined,
    },
    "header-04": {
      name: "header-04",
      description: "header block",
      type: "registry:block",
      registryDependencies: ["button","sheet"],
      files: [{
        path: "registry/default/blocks/header-04/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/header-04/components/header-four.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/header-04/components/contact-form.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["header"],
      component: React.lazy(() => import("@/registry/default/blocks/header-04/page.tsx")),
      source: "__registry__/default/blocks/header-04/page.tsx",
      meta: undefined,
    },
    "logo-01": {
      name: "logo-01",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/logo-01/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/logo-01/components/logo-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/logo-01/components/marquee.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo-01/page.tsx")),
      source: "__registry__/default/blocks/logo-01/page.tsx",
      meta: undefined,
    },
    "logo-02": {
      name: "logo-02",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/logo-02/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/logo-02/components/logo-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/logo-02/components/marquee.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/logo-02/components/tailwind.config.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo-02/page.tsx")),
      source: "__registry__/default/blocks/logo-02/page.tsx",
      meta: undefined,
    },
    "logo-03": {
      name: "logo-03",
      description: "logo-cloud block",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/logo-03/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/logo-03/components/logo-three.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/logo-03/components/logo-slider.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["company-logo"],
      component: React.lazy(() => import("@/registry/default/blocks/logo-03/page.tsx")),
      source: "__registry__/default/blocks/logo-03/page.tsx",
      meta: undefined,
    },
    "login-02": {
      name: "login-02",
      description: "A simple login form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/login-02/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/blocks/login-02/components/login-form-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/login-02/components/google-logo.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["login"],
      component: React.lazy(() => import("@/registry/default/blocks/login-02/page.tsx")),
      source: "__registry__/default/blocks/login-02/page.tsx",
      meta: undefined,
    },
    "newsletter-01": {
      name: "newsletter-01",
      description: "newsletter block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/newsletter-01/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/newsletter-01/components/newsletter-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter-01/page.tsx")),
      source: "__registry__/default/blocks/newsletter-01/page.tsx",
      meta: undefined,
    },
    "newsletter-02": {
      name: "newsletter-02",
      description: "newsletter block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/newsletter-02/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/newsletter-02/components/newsletter-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/newsletter-02/components/user-image.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter-02/page.tsx")),
      source: "__registry__/default/blocks/newsletter-02/page.tsx",
      meta: undefined,
    },
    "newsletter-03": {
      name: "newsletter-03",
      description: "newsletter block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/newsletter-03/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/newsletter-03/components/newsletter-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["newsletter"],
      component: React.lazy(() => import("@/registry/default/blocks/newsletter-03/page.tsx")),
      source: "__registry__/default/blocks/newsletter-03/page.tsx",
      meta: undefined,
    },
    "pricing-01": {
      name: "pricing-01",
      description: "pricing block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/pricing-01/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/pricing-01/components/pricing-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/pricing-01/components/price-slider.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing-01/page.tsx")),
      source: "__registry__/default/blocks/pricing-01/page.tsx",
      meta: undefined,
    },
    "pricing-02": {
      name: "pricing-02",
      description: "pricing block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/pricing-02/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/pricing-02/components/pricing-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing-02/page.tsx")),
      source: "__registry__/default/blocks/pricing-02/page.tsx",
      meta: undefined,
    },
    "pricing-03": {
      name: "pricing-03",
      description: "pricing block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/pricing-03/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/pricing-03/components/pricing-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing-03/page.tsx")),
      source: "__registry__/default/blocks/pricing-03/page.tsx",
      meta: undefined,
    },
    "pricing-04": {
      name: "pricing-04",
      description: "pricing block 4",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/pricing-04/page.tsx",
        type: "registry:page",
        target: ""
      },{
        path: "registry/default/blocks/pricing-04/components/pricing-four.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["pricing"],
      component: React.lazy(() => import("@/registry/default/blocks/pricing-04/page.tsx")),
      source: "__registry__/default/blocks/pricing-04/page.tsx",
      meta: undefined,
    },
    "rating-01": {
      name: "rating-01",
      description: "rating block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/rating-01/page.tsx",
        type: "registry:page",
        target: "@/components/rating.tsx"
      },{
        path: "registry/default/blocks/rating-01/components/rating-one.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/rating-01/hooks/useClickOutside.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating-01/page.tsx")),
      source: "__registry__/default/blocks/rating-01/page.tsx",
      meta: undefined,
    },
    "rating-02": {
      name: "rating-02",
      description: "rating block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/rating-02/page.tsx",
        type: "registry:page",
        target: "@/components/rating.tsx"
      },{
        path: "registry/default/blocks/rating-02/components/rating-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating-02/page.tsx")),
      source: "__registry__/default/blocks/rating-02/page.tsx",
      meta: undefined,
    },
    "rating-03": {
      name: "rating-03",
      description: "rating block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/rating-03/page.tsx",
        type: "registry:page",
        target: "@/components/rating.tsx"
      },{
        path: "registry/default/blocks/rating-03/components/rating-three.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/rating-03/components/dialog-box.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/rating-03/components/write-review.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/rating-03/hooks/useClickOutside.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["rating"],
      component: React.lazy(() => import("@/registry/default/blocks/rating-03/page.tsx")),
      source: "__registry__/default/blocks/rating-03/page.tsx",
      meta: undefined,
    },
    "roadmap-01": {
      name: "roadmap-01",
      description: "roadmap block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/roadmap-01/page.tsx",
        type: "registry:page",
        target: "@/components/roadmap.tsx"
      },{
        path: "registry/default/blocks/roadmap-01/components/roadmap-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap-01/page.tsx")),
      source: "__registry__/default/blocks/roadmap-01/page.tsx",
      meta: undefined,
    },
    "roadmap-02": {
      name: "roadmap-02",
      description: "roadmap block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/roadmap-02/page.tsx",
        type: "registry:page",
        target: "@/components/roadmap.tsx"
      },{
        path: "registry/default/blocks/roadmap-02/components/roadmap-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap-02/page.tsx")),
      source: "__registry__/default/blocks/roadmap-02/page.tsx",
      meta: undefined,
    },
    "roadmap-03": {
      name: "roadmap-03",
      description: "roadmap block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/roadmap-03/page.tsx",
        type: "registry:page",
        target: "@/components/roadmap.tsx"
      },{
        path: "registry/default/blocks/roadmap-03/components/roadmap-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["roadmap"],
      component: React.lazy(() => import("@/registry/default/blocks/roadmap-03/page.tsx")),
      source: "__registry__/default/blocks/roadmap-03/page.tsx",
      meta: undefined,
    },
    "stats-01": {
      name: "stats-01",
      description: "stats block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/stats-01/page.tsx",
        type: "registry:page",
        target: "@/components/stats.tsx"
      },{
        path: "registry/default/blocks/stats-01/components/stats-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats-01/page.tsx")),
      source: "__registry__/default/blocks/stats-01/page.tsx",
      meta: undefined,
    },
    "stats-02": {
      name: "stats-02",
      description: "stats block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/stats-02/page.tsx",
        type: "registry:page",
        target: "@/components/stats.tsx"
      },{
        path: "registry/default/blocks/stats-02/components/stats-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats-02/page.tsx")),
      source: "__registry__/default/blocks/stats-02/page.tsx",
      meta: undefined,
    },
    "stats-03": {
      name: "stats-03",
      description: "stats block 3",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/stats-03/page.tsx",
        type: "registry:page",
        target: "@/components/stats.tsx"
      },{
        path: "registry/default/blocks/stats-03/components/stats-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["stats"],
      component: React.lazy(() => import("@/registry/default/blocks/stats-03/page.tsx")),
      source: "__registry__/default/blocks/stats-03/page.tsx",
      meta: undefined,
    },
    "steps-01": {
      name: "steps-01",
      description: "steps block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/steps-01/page.tsx",
        type: "registry:page",
        target: "@/components/steps.tsx"
      },{
        path: "registry/default/blocks/steps-01/components/steps-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["steps"],
      component: React.lazy(() => import("@/registry/default/blocks/steps-01/page.tsx")),
      source: "__registry__/default/blocks/steps-01/page.tsx",
      meta: undefined,
    },
    "steps-02": {
      name: "steps-02",
      description: "steps block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/steps-02/page.tsx",
        type: "registry:page",
        target: "@/components/steps.tsx"
      },{
        path: "registry/default/blocks/steps-02/components/steps-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["steps"],
      component: React.lazy(() => import("@/registry/default/blocks/steps-02/page.tsx")),
      source: "__registry__/default/blocks/steps-02/page.tsx",
      meta: undefined,
    },
    "signup-01": {
      name: "signup-01",
      description: "A simple Signup form.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/blocks/signup-01/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-01/components/signup-one.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-01/page.tsx")),
      source: "__registry__/default/blocks/signup-01/page.tsx",
      meta: undefined,
    },
    "signup-02": {
      name: "signup-02",
      description: "A Signup form with Password Validation.",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","hover-card"],
      files: [{
        path: "registry/default/blocks/signup-02/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-02/components/signup-two.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-02/page.tsx")),
      source: "__registry__/default/blocks/signup-02/page.tsx",
      meta: undefined,
    },
    "signup-03": {
      name: "signup-03",
      description: "A Signup form with Step",
      type: "registry:block",
      registryDependencies: ["button","input","label"],
      files: [{
        path: "registry/default/blocks/signup-03/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-03/components/signup-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-03/page.tsx")),
      source: "__registry__/default/blocks/signup-03/page.tsx",
      meta: undefined,
    },
    "signup-04": {
      name: "signup-04",
      description: "A Signup form",
      type: "registry:block",
      registryDependencies: ["button","card","input","label","checkbox"],
      files: [{
        path: "registry/default/blocks/signup-04/page.tsx",
        type: "registry:page",
        target: "app/signup/page.tsx"
      },{
        path: "registry/default/blocks/signup-04/components/signup-four.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["signup"],
      component: React.lazy(() => import("@/registry/default/blocks/signup-04/page.tsx")),
      source: "__registry__/default/blocks/signup-04/page.tsx",
      meta: undefined,
    },
    "testimonial-02": {
      name: "testimonial-02",
      description: "testimonial block 1",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/testimonial-02/page.tsx",
        type: "registry:page",
        target: "@/components/testimonial.tsx"
      },{
        path: "registry/default/blocks/testimonial-02/components/testimonial-two.tsx",
        type: "registry:component",
        target: ""
      },{
        path: "registry/default/blocks/testimonial-02/components/testimonial-card.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["testimonial"],
      component: React.lazy(() => import("@/registry/default/blocks/testimonial-02/page.tsx")),
      source: "__registry__/default/blocks/testimonial-02/page.tsx",
      meta: undefined,
    },
    "testimonial-03": {
      name: "testimonial-03",
      description: "testimonial block 2",
      type: "registry:block",
      registryDependencies: [],
      files: [{
        path: "registry/default/blocks/testimonial-03/page.tsx",
        type: "registry:page",
        target: "@/components/testimonial.tsx"
      },{
        path: "registry/default/blocks/testimonial-03/components/testimonial-three.tsx",
        type: "registry:component",
        target: ""
      }],
      categories: ["testimonial"],
      component: React.lazy(() => import("@/registry/default/blocks/testimonial-03/page.tsx")),
      source: "__registry__/default/blocks/testimonial-03/page.tsx",
      meta: undefined,
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      categories: undefined,
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      meta: undefined,
    },
  },
}
